//
// Created by R1300-W-8-Stud on 16.03.2023.
//

#ifndef VM1_RECTMETHODTYPE_H
#define VM1_RECTMETHODTYPE_H

enum RectMethodType {
    LEFT_RECTANGULAR,
    RIGHT_RECTANGULAR,
    MIDDLE_RECTANGULAR
};

#endif //VM1_RECTMETHODTYPE_H
