//
// Created by artem on 11.02.2023.
//

#ifndef VM1_DIAGONALDOMINANCESTATUS_H
#define VM1_DIAGONALDOMINANCESTATUS_H

enum DiagonalDominanceStatus {
    DIAGONAL_DOMINANCE_INITIALLY_PRESENT = 0,
    DIAGONAL_DOMINANCE_IS_NOT_REACHABLE = -1,
    DIAGONAL_DOMINANCE_WAS_REACHED = 1
};

#endif //VM1_DIAGONALDOMINANCESTATUS_H
